const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const money = (n: number) => new Intl.NumberFormat("en-US", {style:"currency",currency:"USD"}).format((n || 0)/100);

export function confirmationEmail(registration: Record<string, any>) {
  const r = registration;
  const status = String(r.registration_status || "").replaceAll("_", " ");
  const text = `Your 2027 Midwest Marriage Retreat registration\n\nReference: ${r.confirmation_code}\nCouple: ${r.husband_first_name} ${r.husband_last_name} & ${r.wife_first_name} ${r.wife_last_name}\nRegistration status: ${status}\nVerified payments: ${money(r.verified_paid_cents)}\nRemaining balance: ${money(r.balance_cents)}\n\nThis is a copy of your existing registration confirmation. No new registration or payment has been created.\nYour registration and room are secured only after the required deposit has been received and verified.\n\nView current registration details, payment instructions, and payments: https://onceuponacovenant.org/manage\n\nOctober 8–10, 2027\nEmbassy Suites Noblesville Indianapolis Conference Center\nQuestions: marriagebydesignministry@myeccoc.com`;
  return { subject:"Your 2027 retreat registration confirmation", text,
    html:`<html lang="en"><body><div style="font-family:Arial,sans-serif;font-size:16px;line-height:1.6;max-width:620px;margin:auto;color:#2d2430"><h1 style="color:#54143d">Once Upon a Covenant</h1><p>Your 2027 Midwest Marriage Retreat registration</p><p><strong>Reference:</strong> ${escape(r.confirmation_code)}</p><p><strong>Couple:</strong> ${escape(r.husband_first_name)} ${escape(r.husband_last_name)} &amp; ${escape(r.wife_first_name)} ${escape(r.wife_last_name)}</p><p><strong>Registration status:</strong> ${escape(status)}<br><strong>Verified payments:</strong> ${money(r.verified_paid_cents)}<br><strong>Remaining balance:</strong> ${money(r.balance_cents)}</p><p>This is a copy of your existing registration confirmation. No new registration or payment has been created.</p><p>Your registration and room are secured only after the required deposit has been received and verified.</p><p><a href="https://onceuponacovenant.org/manage" style="color:#54143d;font-weight:bold">View registration, payment instructions, and balance</a></p><p>October 8–10, 2027<br>Embassy Suites Noblesville Indianapolis Conference Center</p><p>Questions? <a href="mailto:marriagebydesignministry@myeccoc.com">Contact the retreat team</a>.</p></div></body></html>` };
}
